current:
  app_id: hyprctl -j activewindow | jq -r '.class'
  title: hyprctl -j activewindow | jq -r '.title'

llm:
  api_url: "https://api.openai.com/v1/chat/completions"
  default_model: "gpt-4.1-mini"
  timeout: 20

timeouts:
  transcription: 30
  clipboard: 0.05
  sentence_delay: 0.5

generic_paste:
  paste_with: "Ctrl+V"
  paste_sentences: false
