current:
  app_id: niri msg focused-window | grep "App ID" | awk -F'"' '{print $2}' 
  title: niri msg focused-window | grep "Title" | awk -F'"' '{print $2}'

llm:
  api_url: "https://api.openai.com/v1/chat/completions"
  default_model: "gpt-4.1-mini"
  timeout: 20

timeouts:
  transcription: 30
  clipboard: 0.05
  sentence_delay: 0.5

generic_paste:
  paste_with: "Ctrl+V"
  paste_sentences: false